name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # Giải mã file state.json từ Secret
    - name: Restore Auth State from Secret
      run: |
        mkdir -p ./user_data
        echo "${{ secrets.STORAGE_STATE }}" | base64 --decode > ./user_data/state.json

    - name: Run Playwright tests
      run: npx playwright test
      env:
        CI: true

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30