name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Dependencies
      shell: cmd
      run: npm install

    # Copy session state.json từ đường dẫn cố định trên máy local vào thư mục làm việc của Runner
    - name: Copy Local Storage State
      shell: cmd
      run: |
        if not exist "user_data" mkdir user_data
        copy "D:\Work\Moonstake\user_data\state.json" "user_data\state.json"

    - name: Run Playwright Tests
      shell: cmd
      run: npx playwright test tests/asset.spec.ts